<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <VersionPrefix>1.0.2</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdonisUI.ClassicTheme" Version="1.17.1" />
    <PackageReference Include="ReactiveProperty" Version="8.1.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
    <PackageReference Include="VirtualizingWrapPanel" Version="1.5.7" />
  </ItemGroup>

</Project>
